"""create ai_recommendations

AGRIOS — Migration 026
Tier 6 — AI Module

Table: ai_recommendations
  Structured action recommendations generated by ARIA.
  Unlike insights (read-only notifications), recommendations require the farmer
  to take an explicit action: act, dismiss, or allow to expire.

Status lifecycle: pending → acted | dismissed | expired

DB-04: farm_id ✓  DB-01: soft deletes ✓  DB-05: metadata JSONB ✓  AD-01: UUID PK ✓
"""

import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision = "026"
down_revision = "025"
branch_labels = None
depends_on = None

RECOMMENDATION_STATUS_ENUM = sa.Enum(
    "pending", "acted", "dismissed", "expired",
    name="recommendation_status",
)


def upgrade() -> None:
    RECOMMENDATION_STATUS_ENUM.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "ai_recommendations",
        # ── Identity ─────────────────────────────────────────────────────────
        sa.Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            default=uuid.uuid4,
            nullable=False,
        ),
        # ── Farm + optional flock scoping ─────────────────────────────────────
        sa.Column(
            "farm_id",
            UUID(as_uuid=True),
            sa.ForeignKey("farms.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "flock_id",
            UUID(as_uuid=True),
            sa.ForeignKey("flocks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        # ── Content ───────────────────────────────────────────────────────────
        # Recommendation category (e.g. "vaccination", "feed_adjustment", "harvest_timing")
        sa.Column("recommendation_type", sa.String(50), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("body", sa.Text, nullable=False),
        # Deep-link into the app for the recommended action
        sa.Column("action_label", sa.String(100), nullable=True),
        sa.Column("action_route", sa.String(300), nullable=True),
        # ── Status lifecycle ──────────────────────────────────────────────────
        sa.Column(
            "status",
            RECOMMENDATION_STATUS_ENUM,
            nullable=False,
            server_default="pending",
        ),
        sa.Column("acted_at", sa.TIMESTAMPTZ, nullable=True),
        sa.Column("dismissed_at", sa.TIMESTAMPTZ, nullable=True),
        sa.Column("expires_at", sa.TIMESTAMPTZ, nullable=True),
        # ── Timestamps + soft delete + metadata ───────────────────────────────
        sa.Column(
            "created_at",
            sa.TIMESTAMPTZ,
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMPTZ,
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMPTZ, nullable=True),
        sa.Column(
            "metadata",
            JSONB,
            nullable=False,
            server_default="{}",
        ),
    )

    # Primary query: pending recommendations for a farm
    op.create_index(
        "ix_ai_recommendations_farm_status",
        "ai_recommendations",
        ["farm_id", "status"],
    )
    op.create_index(
        "ix_ai_recommendations_farm_id",
        "ai_recommendations",
        ["farm_id"],
    )
    # Batch expiry job
    op.create_index(
        "ix_ai_recommendations_expires_at",
        "ai_recommendations",
        ["expires_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_ai_recommendations_expires_at", table_name="ai_recommendations")
    op.drop_index("ix_ai_recommendations_farm_id", table_name="ai_recommendations")
    op.drop_index("ix_ai_recommendations_farm_status", table_name="ai_recommendations")
    op.drop_table("ai_recommendations")
    sa.Enum(name="recommendation_status").drop(op.get_bind(), checkfirst=True)
